# Kubernetes Versioning
k8s_version: "{{ lookup('env', 'K8S_VERSION') | default('1.35.0', true) }}"
k8s_version_minor: "v{{ k8s_version | regex_replace('^(\\d+\\.\\d+).*', '\\1') }}"
k8s_package_version: "{{ k8s_version }}-1.1"

# Cluster Identity
cluster_name: "{{ lookup('env', 'K8S_CLUSTER_NAME') }}"
cluster_dns_domain: "cluster.local"

# System Paths & Runtimes
cri_socket: "unix:///var/run/containerd/containerd.sock"
etcd_data_dir: "/var/lib/etcd"
cgroup_driver: "systemd"
