---
- name: Setup Containerd
  hosts:
    - master
  become: yes
  roles:
    - containerd
  tags:
    - k8s
    - all
    - containerd

- name: Setup Network
  hosts:
    - master
  become: yes
  roles:
    - network
  tags:
    - k8s
    - all
    - network

- name: Setup K8S
  hosts:
    - master
  become: yes
  roles:
    - kubeadm
  tags:
    - k8s
    - all
    - kubeadm
