---
- name: Install dependencies
  ansible.builtin.apt:
    name: [apt-transport-https, ca-certificates, curl, gpg]
    state: present

- name: Create keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Kubernetes GPG key
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/{{ k8s_version_minor }}/deb/Release.key"
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: '0644'

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/{{ k8s_version_minor }}/deb/ /"
    state: present
    filename: kubernetes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

# - name: Unhold Kubernetes packages to allow update
#   ansible.builtin.dpkg_selections:
#     name: "{{ item }}"
#     selection: install
#   loop: [kubelet, kubeadm, kubectl]

- name: Install K8s binaries
  ansible.builtin.apt:
    name:
      - "kubelet={{ k8s_package_version }}"
      - "kubeadm={{ k8s_package_version }}"
      - "kubectl={{ k8s_package_version }}"
    state: present
    update_cache: yes

- name: Hold K8s packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: [kubelet, kubeadm, kubectl]
